config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :clients
  resources :products

  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations' 
    }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :orders, dependent: :destroy
    belongs_to :type
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :set_types, only: [:new, :edit, :show, :create] 

  before_action :authenticate_user! #, except: [:index, :show]
  # before_action only: [:edit, :update, :destroy] do
  #   authorize_request(["concierge", "admin"])
  # end
  before_action only: [:destroy, :edit, :update, :index, :show] do
    authorize_request(["admin"])
  end

  # GET /clients or /clients.json
  def index
    @clients = Client.all
    @pagy,@clients = pagy(Client.all)
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)    

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end
   
    def set_types
      @types = Type.all.map{ |t| [t.nombre, t.id] }
    end
    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:nombre, :email, :type_id)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Nombre:</strong>
    <%= client.nombre %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= client.type.nombre %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="my-3">    
    <%= form.select :type_id, options_for_select(@types),
    {include_blank: "Tipo de Cliente"},{required: true, style: "display: block" } %>    
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<h1>Clientes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID Cliente</th>
      <th scope="col">Nombre</th>
      <th scope="col">Correo</th>
      <th scope="col">Tipo</th>
      <th scope="col">Ordenes</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |cliente| %>

    <% if cliente.orders.any? %>
      <tr>
        <td><%= cliente.id %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.type.nombre %></td>
        <td>           
            <% cliente.orders.each do |orden| %>
              <%= orden.id %> <%= link_to "Mostrar el orden", "/orders/#{orden.id}", class:"btn btn-secondary btn-sm" %><br>
            <% end %>
        </td>
        <td><%= link_to "Mostrar el cliente", cliente, class:"btn btn-secondary btn-sm" %></td>
      </tr>
  <% end %>
  <% end %>
  </tbody>
</table> 



<div>
  <%= raw pagy_bootstrap_nav(@pagy)%>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>