config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :clients
  resources :products

  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations' 
    }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :client
  belongs_to :payment

  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :set_payments, only: [:new, :edit, :show, :create]
  before_action :set_products, only: [:new, :edit, :show, :create]
  before_action :authenticate_user! 
  before_action only: [:destroy, :edit, :update,] do
    authorize_request(["admin"])
  end
  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new    
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)  
    @order.client_id = current_user.id
    
    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end
    def set_products
      @products = Product.all.map{ |pr| [pr.nombre, pr.id] }
      #@products = Product.all.select { |pr| pr.cantidad > 0 }.map { |pr| [pr.nombre, pr.id, pr.cantidad] }

    end
    def set_payments
      @payments = Payment.all.map{ |p| [p.nombre, p.id] }
    end
    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:monto_total, :fecha_orden, :product_id, :client_id, :payment_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :monto_total, style: "display: block" %>
    <%= form.text_field :monto_total %>
  </div>

  <div>
    <%= form.label :fecha_orden, style: "display: block" %>
    <%= form.datetime_field :fecha_orden %>
  </div>

  <div class="my-3">   
    <%= form.select :product_id, options_for_select(@products),
    {include_blank: "Producto"},{required: true, style: "display: block" } %> 
  </div>

  <div>
    <%#= form.label :client_id, style: "display: block" %>
    <%#= form.text_field :client_id %>
  </div>

  <div class="my-3">    
    <%= form.select :payment_id, options_for_select(@payments),
    {include_blank: "Tipo de Pago"},{required: true, style: "display: block" } %>    
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">

  <p>
    <strong>Monto total:</strong>
    <%= order.monto_total %>
  </p>

  <p>
    <strong>Fecha orden:</strong>
    <%= order.fecha_orden %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= order.product.nombre %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= order.client.nombre %>
  </p>

  <p>
    <strong>Payment:</strong>
    <%= order.payment.nombre %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>

  <% if current_user.id == order.client_id || current_user.role == "admin" %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
     <% end %>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path, class:"btn btn-secondary" %>
</div>

app/views/orders/show.html.erb
<%= render @order %>

<div>
  <% if current_user.role == "admin" %>  
    <%= link_to "Edit this order", edit_order_path(@order) %> |
    <%= button_to "Destroy this order", @order, method: :delete %>
  <% end %>
  <%= link_to "Back to orders", orders_path, class:"btn btn-secondary" %>

  
</div>