config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :clients
  resources :products

  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations' 
    }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord

    has_many :orders, dependent: :destroy
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  before_action only: [:destroy, :edit, :update, :new, :create] do
    authorize_request(["admin"])
  end
  # GET /products or /products.json
  def index
    @products = Product.all
    @pagy,@products = pagy(Product.all)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:nombre, :precio, :descripcion, :cantidad)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.text_field :precio %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :cantidad, style: "display: block" %>
    <%= form.number_field :cantidad %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Nombre:</strong>
    <%= product.nombre %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= product.precio %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= product.descripcion %>
  </p>

  <p>
    <strong>Cantidad:</strong>
    <%= product.cantidad %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<h1>Lista de Productos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID Producto</th>
      <th scope="col">Nombre</th>
      <th scope="col">Precio</th>
      <th scope="col">Descripción</th>
      <th scope="col">Cantidad</th>      
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |producto| %>
      <tr>
        <td><%= producto.id %></td>
        <td><%= producto.nombre %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.cantidad %></td>         
        <td><%= link_to "Mostrar el producto", producto, class:"btn btn-secondary btn-sm" %></td>
      </tr>
  <% end %>
  </tbody>
</table> 

<div>
  <%= raw pagy_bootstrap_nav(@pagy)%>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<%= render @product %>

<div>
  <% if user_signed_in? && current_user.role == "admin" %>
    <%# if current_user.role == "admin" %>  
      <%= link_to "Edit this product", edit_product_path(@product) %> |
      <%= button_to "Destroy this product", @product, method: :delete %>
    <%# end %>
  <% end %>

  <%= link_to "Back to products", products_path, class:"btn btn-secondary"%>

  
</div>