config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :clients
  resources :products

  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations' 
    }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand ms-5" href="/">Covid Retail</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
            <a class="nav-link" href="/products">Productos</a>
            <% if user_signed_in? %>                  
                <% if current_user.role == "admin" %>     
                    <a class="nav-link" href="/clients">Clientes</a> 
                <% end %>
            <% end %>   
            <a class="nav-link" href="/orders">Ordenes</a>           
          </div>
    </div>
    <div class="collapse navbar-collapse d-md-flex justify-content-md-end me-5" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          
          <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <% if user_signed_in? %>
                Hola <%= current_user.name %>
            <% else %>
                Registrarse o conectarse
            <% end %>
          </button>
          <ul class="dropdown-menu dropdown-menu-dark">
              <% if user_signed_in? %>                  
                <% if current_user.role == "admin" %>                        
                  <li><%= link_to "Agregar producto", new_product_path, class:'dropdown-item' %></li>                  
                <% end %>     
                <li><%= link_to 'Editar su perfil', edit_user_registration_path, class:'dropdown-item' %></li>
                <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class:'dropdown-item', method: :delete %></li>
              <% else %>
                <li><%= link_to 'Iniciar sesión', new_user_session_path, class:'dropdown-item'%></li>
                <li><%= link_to 'Registro', new_user_registration_path, class:'dropdown-item'%></li>
              <% end %>
          </ul>
        </li>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CovidRetail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container mt-5">
    <p class="notice", style="color: green"><%= notice %></p>
      <%= yield %>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>

  </body>
</html>